posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

profiles/urls.py
from django.urls import path
from .views import *

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('myprofile/',my_profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invatation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/acctept/', accept_invatation, name='accept-invite'),
    path('my-invites/reject/', reject_invatation, name='reject-invite'),
]

smedia/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf.urls import include
from django.conf import settings
from.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_view,name='home-view'),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    #path('posts/', include('posts.urls', namespace='posts')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!--Custom css ADD -->
    <link rel="stylesheet" type="text/css" href={% static 'style.css' %}>
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

  
    <title>social - {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="ui container">
      {% block content %}
      {% endblock content %}
    </div>

    {% block scripts %}
    {% endblock scripts %}
   
   <!--Custom js  HERE-->
    <script type="text/javascript" src={% static 'main.js' %}></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %}
{% block title %}
Home
{% endblock title %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif;}
body, html {
  height: 100%;
  color: #777;
  line-height: 1.8;
}

/* Create a Parallax Effect */
.bgimg-1, .bgimg-2, .bgimg-3 {
  background-attachment: fixed;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}

/* First image (Logo. Full height) */
.bgimg-1 {
  background-image: url('https://www.thewowstyle.com/wp-content/uploads/2015/07/Natural-World-Wallpaper-HD-.jpg');
  min-height: 100%;
}

/* Second image (Portfolio) */
.bgimg-2 {
  background-image: url("https://wallup.net/wp-content/uploads/2019/05/10/994278-beautiful-nature-forest-house-autumn-amazing-beauty-waterfall-landscape.jpg");
  min-height: 400px;
}

/* Third image (Contact) */
.bgimg-3 {
  background-image: url("https://wallup.net/wp-content/uploads/2016/01/25469-nature-landscape-Earth-water-sea.jpg");
  min-height: 400px;
}

.w3-wide {letter-spacing: 10px;}
.w3-hover-opacity {cursor: pointer;}

/* Turn off parallax scrolling for tablets and phones */
@media only screen and (max-device-width: 1600px) {
  .bgimg-1, .bgimg-2, .bgimg-3 {
    background-attachment: scroll;
    min-height: 400px;
  }
}
</style>
<body>

<!-- First Parallax Image with Logo Text -->
<div class="bgimg-1 w3-display-container w3-opacity-min" id="home">
  <div class="w3-display-middle" style="white-space:nowrap;">
    <span class="w3-center w3-padding-large w3-black w3-xlarge w3-wide w3-animate-opacity">Social<span class="w3-hide-small">Media</span>Web</span>
  </div>
</div>

<!-- Container (About Section) -->
<div class="w3-content w3-container w3-padding-64" id="about">
  <h3 class="w3-center"></h3>
  <p class="w3-center"><em></em></p>
  <p>Social Media</p>
  <div class="w3-row">
    <div class="w3-col m6 w3-center w3-padding-large">
      <p><b><i class="fa fa-user w3-margin-right"></i></b></p><br>
      <img src="https://images3.alphacoders.com/823/thumb-1920-82317.jpg" class="w3-round w3-image w3-opacity w3-hover-opacity-off" alt="Photo of Me" width="500" height="333">
    </div>

    <!-- Hide this text on small devices -->
    <div class="w3-col m6 w3-hide-small w3-padding-large">
      <p></p>
    </div>
  </div>
  <p class="w3-large w3-center w3-padding-16"></p>
  <p class="w3-wide"><i class="fa fa-camera"></i></p>
  <div class="w3-light-grey">
    <div class="w3-container w3-padding-small w3-dark-grey w3-center" style="width:90%"></div>
  </div>
  <p class="w3-wide"><i class="fa fa-laptop"></i></p>
  <div class="w3-light-grey">
    <div class="w3-container w3-padding-small w3-dark-grey w3-center" style="width:85%"></div>
  </div>
  <p class="w3-wide"><i class="fa fa-photo"></i></p>
  <div class="w3-light-grey">
    <div class="w3-container w3-padding-small w3-dark-grey w3-center" style="width:75%"></div>
  </div>
</div>

<div class="w3-row w3-center w3-dark-grey w3-padding-16">
  <div class="w3-quarter w3-section">
    <span class="w3-xlarge"></span><br>
    
  </div>
  <div class="w3-quarter w3-section">
    <span class="w3-xlarge"></span><br>
    
  </div>
  <div class="w3-quarter w3-section">
    <span class="w3-xlarge"></span><br>
  </div>
  <div class="w3-quarter w3-section">
    <span class="w3-xlarge"></span><br>
  </div>
</div>

<!-- Second Parallax Image with Portfolio Text -->
<div class="bgimg-2 w3-display-container w3-opacity-min">
  <div class="w3-display-middle">
    <span class="w3-xxlarge w3-text-white w3-wide"></span>
  </div>
</div>

<!-- Container (Portfolio Section) -->
<div class="w3-content w3-container w3-padding-64" id="portfolio">
  <h3 class="w3-center"></h3>
  <p class="w3-center"><em><br> </em></p><br>

  <!-- Responsive Grid. Four columns on tablets, laptops and desktops. Will stack on mobile devices/small screens (100% width) -->
  <div class="w3-row-padding w3-center">
    <div class="w3-col m3">
      <img src="https://weneedfun.com/wp-content/uploads/2016/09/Amazing-Photos-Of-Nature-12.jpg" style="width:100%" onclick="onClick(this)" class="w3-hover-opacity" alt="The mist over the mountains">
    </div>

    <div class="w3-col m3">
      <img src="https://www.thewowstyle.com/wp-content/uploads/2015/07/natural-landscape-purple-lake-wallpaper-.jpg" style="width:100%" onclick="onClick(this)" class="w3-hover-opacity" alt="Coffee beans">
    </div>

    <div class="w3-col m3">
      <img src="https://www.wallpapers13.com/wp-content/uploads/2016/01/Cool-and-Beautiful-Nature-desktop-wallpaper-image-2560X1600-1680x1050.jpg" style="width:100%" onclick="onClick(this)" class="w3-hover-opacity" alt="Bear closeup">
    </div>

    <div class="w3-col m3">
      <img src="https://wallpapercave.com/wp/ylvyN1V.jpg" style="width:100%" onclick="onClick(this)" class="w3-hover-opacity" alt="Quiet ocean">
    </div>
  </div>

  <div class="w3-row-padding w3-center w3-section">
    <div class="w3-col m3">
      <img src="https://wallup.net/wp-content/uploads/2016/03/10/314622-nature-sea-Photoshop.jpg" style="width:100%" onclick="onClick(this)" class="w3-hover-opacity" alt="The mist">
    </div>

    <div class="w3-col m3">
      <img src="https://thewallpaper.co/wp-content/uploads/2020/09/hd-nature-images-wallpaper-of-natures-plants-fresh-air-widescreen-wallpapers-windows-nature-wallpapers-plant-background-images-organic-life-1440x967-1.jpg" style="width:100%" onclick="onClick(this)" class="w3-hover-opacity" alt="My beloved typewriter">
    </div>

    <div class="w3-col m3">
      <img src="https://wallup.net/wp-content/uploads/2016/01/47222-anime-landscape-nature.jpg" style="width:100%" onclick="onClick(this)" class="w3-hover-opacity" alt="Empty ghost train">
    </div>

    <div class="w3-col m3">
      <img src="https://www.pixelstalk.net/wp-content/uploads/2016/07/3d-nature-photos-hd-download-1.jpg" style="width:100%" onclick="onClick(this)" class="w3-hover-opacity" alt="Sailing">
    </div>
    <button class="w3-button w3-padding-large w3-light-grey" style="margin-top:64px">LOAD MORE</button>
  </div>
</div>

<!-- Modal for full size images on click-->
<div id="modal01" class="w3-modal w3-black" onclick="this.style.display='none'">
  <span class="w3-button w3-large w3-black w3-display-topright" title="Close Modal Image"><i class="fa fa-remove"></i></span>
  <div class="w3-modal-content w3-animate-zoom w3-center w3-transparent w3-padding-64">
    <img id="img01" class="w3-image">
    <p id="caption" class="w3-opacity w3-large"></p>
  </div>
</div>

<!-- Third Parallax Image with Portfolio Text -->
<div class="bgimg-3 w3-display-container w3-opacity-min">
  <div class="w3-display-middle">
     <span class="w3-xxlarge w3-text-white w3-wide"></span>
  </div>
</div>

<!-- Container (Contact Section) -->
<div class="w3-content w3-container w3-padding-64" id="contact">
  <h3 class="w3-center"></h3>
  <p class="w3-center"><em></em></p>

  <div class="w3-row w3-padding-32 w3-section">
    <div class="w3-col m4 w3-container">
      <img src="https://www.desktopbackground.org/download/1600x900/2012/09/10/450552_high-resolution-nature-wallpapers-natural-landscape-amazing_1697x1015_h.jpg" class="w3-image w3-round" style="width:100%">
    </div>
    <div class="w3-col m8 w3-panel">
      <div class="w3-large w3-margin-bottom">
      </div>
    </div>
  </div>
</div>

<!-- Footer -->
<footer class="w3-center w3-black w3-padding-64 w3-opacity w3-hover-opacity-off">
  <a href="#home" class="w3-button w3-light-grey"><i class="fa fa-arrow-up w3-margin-right"></i></a>
  <div class="w3-xlarge w3-section">
  </div>
</footer>
 
<script>
// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}

// Change style of navbar on scroll
window.onscroll = function() {myFunction()};
function myFunction() {
    var navbar = document.getElementById("myNavbar");
    if (document.body.scrollTop > 100 || document.documentElement.scrollTop > 100) {
        navbar.className = "w3-bar" + " w3-card" + " w3-animate-top" + " w3-white";
    } else {
        navbar.className = navbar.className.replace(" w3-card w3-animate-top w3-white", "");
    }
}

// Used to toggle the menu on small screens when clicking on the menu button
function toggleFunction() {
    var x = document.getElementById("navDemo");
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else {
        x.className = x.className.replace(" w3-show", "");
    }
}
</script>

</body>
</html>

{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block admin_change_form_document_ready %}
{{ block.super }}
    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <script src="{% static 'jquery.easing.min.js' %}"></script>
    <script src="{% static 'theme.js' %}"></script>
    <script src="{% static 'validate.js' %}"></script>
{% endblock %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ZuChristmas - Free Christmas Landing Page</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstarp.min.css' %}">

    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Varela:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli|Great+Vibes|Marmelad" rel="stylesheet">

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Theme CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'theme.css' %}" >

</head>

<body id="page-top">


<div class="illustration">
	<div class="i-large"></div>
	<div class="i-medium"></div>
	<div class="i-small"></div>
</div>



    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top"><img class="iconlogo" src="img/iconlogo.png" width="50"> ZU CHRISTMAS</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#coupon">Special Offer</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#faq">F.A.Q.</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                    <li>
                        <a target="_blank" href="http://www.zuthemes.com/freebies/zuchristmas-free-landing-page-for-holidays/" class="menuhighlight"><i class="fa fa-cloud-download"></i> Download</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="container">
            <div class="row">
              <div class="col-sm-6">
                <div class="device-container">
                <img class="img-responsive" src="img/homeimg.png">
              </div>
              </div>
                <div class="col-sm-6">
                    <div class="header-content">
                        <div class="header-content-inner">
                            <h1>Merry Holidays</h1>
                            <h4>Make your visitors smile with this special landing page!</h4>
                            <br/>
                            <a href="#" class="btnimg"><img src="img/button-available.png" height="50"></a>   <a href="#" class="btnimg"><img src="img/button-googleplay.png" height="50"></a>
                          <br/>
                          <br/>
                          <div class="social">
                          <a href="#"><i class="fa fa-facebook"></i></a>
                          <a href="#"><i class="fa fa-twitter"></i></a>
                          <a href="#"><i class="fa fa-google-plus"></i></a>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="audioembed">
          <audio controls="true" autoplay="true" src="audio.mp3"  onloadeddata="setLowVolume()" id="audio1">
        </div>
      </header>

    <section id="coupon" class="couponsection bg-primary text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <h2 class="title section-heading">December Only</h2>
                    <p>Get your discount, available in stores this month only</p>
                    <div class="coupon">
                      <img src="img/gift.png">
                    	<h3>50% Off All Themes!</h3>
                      <h4>Coupon Code: <span style="border-bottom:1px dashed">ZUTHEMES50</span> </h4>
                      <br/>
                    	<p><i>Use this coupon code at checkout to receive<br/> <u>half off</u> your Zu Themes order. Hurry up, limited order!</i></p>
                      <p><a href="http://www.zuthemes.com" class="btn btn-buynow"><i class="fa fa-shopping-cart"></i> Shop Now</a>

                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="faq">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="section-heading">
                        <h2 class="title">F.A.Q.</h2>
                        <p class="text-muted">Contact us if you have a different question</p>
                        <img src="img/sep.png" width="120">
                    </div>
                </div>
            </div>
            <div class="col-md-10 col-md-offset-1">
            <div class="row">
                <div class="col-md-6">
                  <h3>How soon do I get my item?</h3>
                  <p> If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.</p>

                  <h3>Is there a free shipping?</h3>
                  <p> If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.</p>

                  <h3>Can I get several discounts?</h3>
                  <p> If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.</p>


                </div>
                <div class="col-md-6">
                  <h3>Do you deliver it as a gift?</h3>
                  <p> If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.</p>

                  <h3>What payment methods?</h3>
                  <p> If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.</p>

                  <h3>I have a different question?</h3>
                  <p> If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.</p>

                </div>
            </div>
          </div>
    </section>

    <section id="contact">
            <div class="container">
              <div class="row">
                  <div class="col-lg-12 text-center">
                      <div class="section-heading">
                          <h2 class="title" style="margin-bottom:60px;color:#fff;">Contact Us</h2>
                      </div>
                  </div>
              </div>
              <div class="col-lg-8 col-lg-offset-2">
                <div class="done">
                  <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    Your message has been sent. Thank you!
                  </div>
                </div>
                <form method="post" action="contact.php" id="contactform">
                  <div class="form">
                    <div class="row">
                      <div class="col-md-6">
                        <input type="text" name="name" placeholder="Name *">
                      </div>
                      <div class="col-md-6">
                        <input type="text" name="email" placeholder="E-mail *">
                      </div>
                    </div>
                    <textarea name="comment" rows="7" placeholder="Message *"></textarea>
                    <input type="submit" id="submit" class="clearfix btn" value="Send">
                  </div>
                </form>
              </div>
            </div>
            <div class="overlay"></div>
    </section>


    <footer>
        <div class="container">
            <p>&copy; 2017 ZuChristmas by ZuThemes. All Rights Reserved.</p>
            <ul class="list-inline">
                <li>
                    <a href="#">Privacy</a>
                </li>
                <li>
                    <a href="#">Terms</a>
                </li>
                <li>
                    <a href="#">FAQ</a>
                </li>
            </ul>
        </div>
    </footer>

    <!-- jQuery -->

</body>

</html>
{% endblock content %}

templates/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}
{% url 'profiles:invite-profiles-view' as path_to_invites %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}

<div class="ui inverted menu nav mb-7">
  <div class="ui container">
    <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
        <h3>Social</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
        Posts
    </a>
    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Friends
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                        All Profiles
                    </a>
                    <a href="{{path_to_invites}}" class="{% if request.path == path_to_invites %}active{% endif %} item">
                        Send Invites
                    </a>
                    <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                        Received Invites &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                    </a>
                </div>
             </div>
        </div>
             <div class="item">
              <form action="" method="GET">
                <div class="ui action left icon input">
                <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                <i class="search icon"></i>
                <button type='submit' class="ui button">Search</button>
                </div>
            </form>
            </div>
        
            <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                <img src={{picture.url}} class="ui avatar image">&nbsp;
                 {{ request.user }}
            </a>

            <a href="{% url 'account_logout' %}" class="ui item">
                Logout
            </a>
        {% else %}
        <a href="{% url 'account_login' %}" class="ui item">
                Login
            </a>
        {% endif %}
    </div>
  </div>
</div>